// /api/endorse-action.js
// Clinician edit/reject endpoint, authenticated by per-row action_token.
//
// The action_token is a 64-char hex nonce auto-generated by a Postgres
// trigger on endorsement insert. It's emailed to the practice's primary
// contact so they can correct metadata or remove the endorsement without
// logging in. The token is stored unique on endorsements.action_token; we
// do constant-time compare via Postgres equality.
//
// Editable fields (clinician's "fix typos" capability):
//   endorser_name, endorser_credentials, endorser_title, endorser_org
// Locked fields (preserve authenticity):
//   content, endorser_links, endorser_image_id/url, display_scope
//
// Operations:
//   GET  ?token=<...>                → returns endorsement + clinician/practice context
//   POST { token, op:'edit', ...}    → patch metadata, sets edited_at + edited_fields
//   POST { token, op:'reject' }      → status='rejected', removes from rendered output
//
// All routes are public (no admin auth, no page-token cookie). The token IS
// the auth. Rate-limited per IP.

var sb        = require('./_lib/supabase');
var sanitizer = require('./_lib/html-sanitizer');
var rateLimit = require('./_lib/rate-limit');
var monitor   = require('./_lib/monitor');

var TOKEN_RE = /^[0-9a-f]{64}$/i;

var EDITABLE_FIELDS = ['endorser_name', 'endorser_credentials', 'endorser_title', 'endorser_org'];
var LIMITS = {
  endorser_name:        200,
  endorser_credentials: 200,
  endorser_title:       200,
  endorser_org:         200
};

module.exports = async function handler(req, res) {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', 'https://clients.moonraker.ai');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    return res.status(200).end();
  }
  if (req.method !== 'GET' && req.method !== 'POST') {
    res.setHeader('Allow', 'GET, POST');
    return res.status(405).json({ error: 'Method not allowed' });
  }

  if (!sb.isConfigured()) return res.status(500).json({ error: 'Service unavailable' });

  // Token comes from query (GET) or body (POST). Same validation either way.
  var src = req.method === 'GET' ? (req.query || {}) : (req.body || {});
  var token = String(src.token || '').trim().toLowerCase();

  if (!TOKEN_RE.test(token)) {
    return res.status(400).json({ error: 'Invalid token format' });
  }

  // Rate limit: 60/hour per IP. Generous for normal use (page load + a few
  // edits + a confirm), tight enough that a leaked token can't be hammered.
  var ip = (req.headers['x-forwarded-for'] || '').split(',')[0].trim() || 'unknown';
  try {
    var rl = await rateLimit.check('endorse-action:ip:' + ip, 60, 3600, { failClosed: false });
    if (rl && rl.allowed === false) {
      res.setHeader('Retry-After', '60');
      return res.status(429).json({ error: 'Too many requests' });
    }
  } catch (_) {}

  // Look up the endorsement by token. Single source of truth.
  var endorsement;
  try {
    endorsement = await sb.one(
      'endorsements?action_token=eq.' + encodeURIComponent(token) + '&limit=1'
    );
  } catch (e) {
    monitor.logError('endorse-action', e, { detail: { stage: 'token_lookup' } });
    return res.status(500).json({ error: 'Lookup failed' });
  }
  if (!endorsement) {
    return res.status(404).json({ error: 'This link is no longer valid.' });
  }

  if (req.method === 'GET') return handleGet(req, res, endorsement);

  // POST routes
  var op = String((req.body && req.body.op) || '').toLowerCase();
  if (op === 'edit')   return handleEdit(req, res, endorsement);
  if (op === 'reject') return handleReject(req, res, endorsement);
  return res.status(400).json({ error: 'Unknown operation' });
};

// ── GET: return endorsement + display context for the page ─────────
async function handleGet(req, res, endorsement) {
  var contact, bm;
  try {
    contact = await sb.one(
      'contacts?id=eq.' + encodeURIComponent(endorsement.contact_id) +
      '&select=slug,practice_name&limit=1'
    );
    if (endorsement.bio_material_id) {
      bm = await sb.one(
        'bio_materials?id=eq.' + encodeURIComponent(endorsement.bio_material_id) +
        '&select=therapist_name,slug&limit=1'
      );
    }
  } catch (e) {
    monitor.logError('endorse-action', e, { detail: { stage: 'get_context', endorsement_id: endorsement.id } });
    return res.status(500).json({ error: 'Lookup failed' });
  }

  return res.status(200).json({
    ok: true,
    endorsement: {
      id: endorsement.id,
      status: endorsement.status,
      content: endorsement.content,
      endorser_name:        endorsement.endorser_name        || '',
      endorser_credentials: endorsement.endorser_credentials || '',
      endorser_title:       endorsement.endorser_title       || '',
      endorser_org:         endorsement.endorser_org         || '',
      endorser_headshot_url: endorsement.endorser_headshot_url || '',
      endorser_links:       endorsement.endorser_links || [],
      submitted_at:         endorsement.submitted_at,
      edited_at:            endorsement.edited_at,
      edited_fields:        endorsement.edited_fields || []
    },
    clinician: {
      name: bm ? (bm.therapist_name || '') : '',
      slug: bm ? (bm.slug || '') : ''
    },
    practice: {
      slug: contact ? (contact.slug || '') : '',
      name: contact ? (contact.practice_name || '') : ''
    }
  });
}

// ── POST op=edit: patch metadata fields, lock content ──────────────
async function handleEdit(req, res, endorsement) {
  if (endorsement.status === 'rejected') {
    return res.status(409).json({ error: 'This endorsement was already removed.' });
  }

  var body = req.body || {};
  var patch = {};
  var changed = [];

  EDITABLE_FIELDS.forEach(function (f) {
    // Only patch fields that were actually included in the request. An
    // empty string is a valid edit (clearing a typo'd field).
    if (Object.prototype.hasOwnProperty.call(body, f)) {
      var raw = body[f];
      if (raw == null) raw = '';
      var clean = sanitizer.sanitizeText(String(raw), LIMITS[f]);
      // Coerce empty strings to null so the column matches insert-time semantics
      var newVal = clean || null;
      var oldVal = endorsement[f] || null;
      if (newVal !== oldVal) {
        patch[f] = newVal;
        changed.push(f);
      }
    }
  });

  // endorser_name has the same NOT-NULL-effective treatment as on submit:
  // we never let it be cleared.
  if (Object.prototype.hasOwnProperty.call(patch, 'endorser_name') && !patch.endorser_name) {
    return res.status(400).json({ error: 'Endorser name cannot be empty.' });
  }

  if (changed.length === 0) {
    return res.status(200).json({ ok: true, changed: [], message: 'No changes.' });
  }

  // Merge with existing edited_fields so cumulative edits are tracked.
  var prevEdited = Array.isArray(endorsement.edited_fields) ? endorsement.edited_fields : [];
  var nextEdited = prevEdited.slice();
  changed.forEach(function (f) {
    if (nextEdited.indexOf(f) === -1) nextEdited.push(f);
  });

  patch.edited_at = new Date().toISOString();
  patch.edited_fields = nextEdited;

  try {
    await sb.mutate(
      'endorsements?id=eq.' + encodeURIComponent(endorsement.id),
      'PATCH',
      patch,
      'return=minimal'
    );
  } catch (e) {
    monitor.logError('endorse-action', e, {
      detail: { stage: 'edit_patch', endorsement_id: endorsement.id, fields: changed }
    });
    return res.status(500).json({ error: 'Could not save changes. Please try again.' });
  }

  return res.status(200).json({ ok: true, changed: changed });
}

// ── POST op=reject: flip to status='rejected' ──────────────────────
async function handleReject(req, res, endorsement) {
  if (endorsement.status === 'rejected') {
    return res.status(200).json({ ok: true, already: true });
  }

  try {
    await sb.mutate(
      'endorsements?id=eq.' + encodeURIComponent(endorsement.id),
      'PATCH',
      {
        status: 'rejected',
        // Clear the action token so the link no longer works after rejection.
        // Once rejected, the clinician shouldn't be able to "un-reject" via
        // the same email link — they'd contact us if they changed their mind.
        action_token: null
      },
      'return=minimal'
    );
  } catch (e) {
    monitor.logError('endorse-action', e, {
      detail: { stage: 'reject_patch', endorsement_id: endorsement.id }
    });
    return res.status(500).json({ error: 'Could not remove the endorsement. Please try again.' });
  }

  return res.status(200).json({ ok: true });
}
